### ISSUE TITLE
[Bug] Profiles are not changing

### ISSUE THREAD

**Issue by PatriQ94** [Krealle/Cell_UnitFrames#116]
### Addon Version

11.0.2

### World of Warcraft Version

Retail

### Describe the bug

The goal was to have Player and Target frames in one position (with specific settings) in 1 Cell layout and another position in a second layout. But I've tried changing the "Master Layout" and set it to "Noone" as well as to those two layouts from Cell, but the frames are just fixed at the same position, same settings whatever I do. 

For example: I've got a "Healing party" layout in Cell and a "Healing raid" layout. I want Party and Target frames to be on different positions with different widths and settings. How to set it up?

### Steps to reproduce

Described above.

**Comment by Krealle** [comment]
I find myself unable to replicate this.
With `None` as the Master Layout I get this position when using my Default layout.
![Image](https://github.com/user-attachments/assets/472d93c7-8485-42cc-b495-41f3915f0309)

And this when using another layout with changed positions.
![Image](https://github.com/user-attachments/assets/a5bd78f3-1c26-44d2-907b-9fb769429941)

Selecting another layout here instead of swapping into another layout doesn't actually load frame positions, that is something I'll look into.
![Image](https://github.com/user-attachments/assets/764b4bb2-999e-452a-bd19-ec3fa3dda53f)

**Comment by PatriQ94** [comment]
![image](https://github.com/user-attachments/assets/b9cfaab8-a5aa-4612-ae1b-c84867f11187)
So theoretically if each of these layouts in the above picture had different positions and settings of Player and Target frames and then having *Master Layout* set to *None* it should work?

**Comment by Krealle** [comment]
That is the behavior that im seeing when i mess around with it yes.
The "bug" is that positioning with "none" selected doesnt respect what is choosen in the layout dropdown, like the rest of the settings do
